version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge


volumes:
  rabbitmq_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./rabbitmq-data/data
  rabbitmq_log:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./rabbitmq-data/log